### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by cyberdyne-sys** [ThirteenAG/III.VC.SA.WindowedMode#4]
For some weird reason, this plugin doesn't work properly for me, without the WidescreenFix plugin, while i'm using the suggested Ultimate ASI Loader, even if i have the latest version of all of them.
More detailed, w/o WSF plugin, i always get an unhandled exception error message, right after the first game loading splash screen:
![](http://i65.tinypic.com/rmobit.jpg)

And after inserting WSF to the scripts folder, both of them seem to be working (WSF worked alone, too):
![](http://i64.tinypic.com/mc956h.jpg)

Anyways, i tried it on a C2D powered laptop, with 4 GB of RAM, a powerful enough ATI HD MXM VGA card and a 15,4" screen. The OS is a Windows 7 32bit. Oh and i got the same results with and w/o a gta_vc.set file.

**Comment by ThirteenAG** [comment]
Can't reproduce this.

**Comment by cyberdyne-sys** [comment]
First of all, thank you for your response.
Well, unfortunatelly, i'm still able to reproduce it every single time, when i use it, without the WSF plugin.
After your answer i thought, maybe the reason of the problem hiding in my system, so i put a fresh and clean Windows 7 Ultimate x64 system - with every available updates for VC++ runtimes (2008-2017), the latest .NET Framework, DirectX updates (both for dx9 and dx11), etc. -, into a VBox VM (properly configured for 3D jobs). The results are even worse, than before, since the WSF plugin still works, like a charm, but the game simply refuses to start with only this plugin and gives a BSOD, combined, with WSF.
WSF plugin in the described virtual environnt above:
![](http://i63.tinypic.com/2qw0sas.png)

Please let me know, if i can contribute, with any other detailes.

**Comment by ThirteenAG** [comment]
No idea what could be causing this. What if you install MVL mod and activate windowed feature there, does it behave the same way?

**Comment by cyberdyne-sys** [comment]
Today i fired up a clean copy of the VM, mentioned earlier and installed the latest (0.99d) version of MVL. It seems, it's working, without any problems. I even tried to change several parameter values randomly in the main config xml, but i couldn't screw it at all.
Main menu:
![](http://i68.tinypic.com/331hbps.png)

A new game:
![](http://i63.tinypic.com/o88ltd.png)

I experienced only a relatively small issue. When i choosed to quit from the game, the quit splash appeared and then MVL's window became unresposive, while gta-vc.exe never exited, so i had to shut it manually, every single time. The same happened anyways, when i clicked on 'X' of the top-right corner of MVL, for closing it (except, that final splash didn't appear obviously):
![](http://i63.tinypic.com/1qk2ae.png)

After all of these, i gone mad and tried to load MVL along, with WSF plugin. The game exe started and stayed running though, but nothing else happened, no UI, or any kind of game graphics showed up.
But, once i lauched the game, with this plugins (with, or w/o MVL), maybe a few times, the frame of it's window popped up for a ms, or two, but then, i instantly got the earlier BSOD, which' stop code is the following:

> *** STOP: 0x00000119 (0x0000000000000001, 0x0000000000000001, 0x0000000000007AC2, 0x0000000000007AC2)

Hope, these new results help somewhat.

**Comment by ThirteenAG** [comment]
Yes, I was able to get that crash. Will check it out.

**Comment by ThirteenAG** [comment]
I released a new version, please try again and let me know if it's working now.

**Comment by cyberdyne-sys** [comment]
Thank you for the fixing attempt, with the new version. I just checked it on the VM (so a VirtualBox one), but unfortunatelly, the story still always ends, with a BSOD. The main part of STOP code is still the same (some kind of a video scheduler issue, which has something to do with DX), only the rest of it is changing randomly.
There's some progress though, cause now, at least the intro is starting in full screen, but as soon, as i push a button, i get BSOD.

**Comment by ThirteenAG** [comment]
Sorry, I'm not getting this on my win7 VM.
![](https://i.imgur.com/SucpoSW.png)

And it's really bizzare that user made program would cause a bsod. Something ain't right here.

**Comment by cyberdyne-sys** [comment]
Yes, it's very strange, that on similar systems and VMs, once it doesn't working - on the top of that, it can even result BSOD -, then it simply does.
I was thinking and thinking, what can cause such a behaviour and what can be different, between our systems. Well, to be honest, i'm still running the version 5.2.12 r122591 of VBox and the appropriate guest additions on the Win 7 Ultimate x64 system. I'll update VBox to the latest, asap., but in the meantime, do you think, it worth to try it on 5.2.12 for you too?
Additionally, the following system-related softwares are installed on my VM:
- all of the VC++ runtimes, both x32 and x64 ones from 2005 to 2017
- most likelí it's irrelevant, but .NET Framework 4.7.1
- DirectX 9.0c (June 2010), last update
- again, it'd not matter, but DirectX 11 update for Win 7 (service package / platform update KB2670838)

The specs of the VM, i'm using for this purpose:
- only 1 CPU core (tried it with 2 though)
- 1,5 GB of RAM
- 256 MB of VRAM  for the virtualbox VGA
- 2D and 3D support are both checked
- VT-x/AMD-V is enabled, since x64 system requires it
- PAE/NX, Memory-virtualization and Hyper-V is turned on, IO APIC enabled
- virtual chipset is ICH9

Anyways, this program should work, with almost any settings of the above ones, but with a system, running on a virtual machine, who knows... we never can be absolutelly sure.

**Comment by ThirteenAG** [comment]
I don't know, I can only suggest trying to see what happens in gta 3 and gta sa and eventually switching to another windowed solution, like creating empty wndmode.ini file in the root folder.

**Comment by cyberdyne-sys** [comment]
I did, what you suggested and tried the wndmode.ini way. No matter, what settings i changed in it, after i enabled Direct3D, BSOD instantly appeared, after the intro movies. Even though, MVL was working in this environment, i got a strong feeling, the defective bit of the puzzle to blame, may be found in VBox itself somehow. So first, i uninstalled guest additions completely and reinstalled it, but this time, only with the VGA driver, with basic Direct3D support, instead of the experimental driver. Well, it seems, it did the trick and all of the plugins are working, combined, or independetly, it doesn't matter. So i assume, you also have only the basic driver on your VM, isn't it?
On the other hand, i think i faced with another little problem, regarding of the mouse cursor toggling, but this is another story, so i'll copy the followings to a new issue ticket, if you want:
For me, Ctrl+Alt key combination doesn't work, like expected. Namely, when launching the game, cursor is turned off and it can be turned on, detaching the window, doing other task, etc., but after that, i'm unable to turning the cursor off again, which results, that player can do view rotations only in a limited angle, since cursor then simply leaves the window area. I have mention to at this point, that VBox's mouse integration is turned off, during this.
Besides, window border toggling is a bit erratic for me. Mostly, it doesn't react for the key combinations of Ctrl+Enter/Shift+Enter. Anyways, Alt+Enter seems to be working perfectly.

**Comment by ThirteenAG** [comment]
For cursor centering you need to install SilentPatch.

**Comment by cyberdyne-sys** [comment]
Are you sure, it's all about cursor centering only? I just ask, cause Ctrl+Alt doesn't turn the regular windows cursor off for me at all, so when the "invisible" pointer reaches the border of the game window, windows cursor appears and game-controlling loses the focus. The same happens, when i run the game on a real PC.
* It's totally irrelevant in here, but i'd like to ask, how can i control the window size, in case of the wndmode method, because the game starts always in fullscreen and i can't switch to windowed mode (while .ini file is filled properly).

**Comment by ThirteenAG** [comment]
>so when the "invisible" pointer reaches the border of the game window, windows cursor appears and game-controlling loses the focus.

Cursor works for me in III and VC, but behaves similarly in SA. I don't know why.


>It's totally irrelevant in here, but i'd like to ask, how can i control the window size, in case of the wndmode method, because the game starts always in fullscreen and i can't switch to windowed mode (while .ini file is filled properly).

Only by changing resolution in menu before the game is loaded.
